# Header

menu:
  homePage: /
  #tags: /tags/
  #categories: /categories/
  #随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/ava-YangL"
  #weibo: "#"
  ##rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "ava_yangli@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUTEhMVFRUVFRAVFRUVFRUVFxUVFRUWFhUVFRUYHSggGBolHRUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGhAQGi0dHR8tLS0tLSstLSstLS0rLS0tLS0tLS0tKy0tLS0tKy0tLS0tLS0rLTctKy03LS0tLTctN//AABEIAOEA4QMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAFAAIDBAYBBwj/xABFEAABAwIDBAYHBQYGAQUBAAABAAIDBBEFEiEGMUFRE2FxgZGxBxQiMkKhwTNSctHwI0Nic4LhFRZTkqKygyRUwuLxF//EABkBAAMBAQEAAAAAAAAAAAAAAAABAgMEBf/EACURAAICAwEAAgMAAgMAAAAAAAABAhESITEDE0EEMlEicSMzYf/aAAwDAQACEQMRAD8AOJAqAzLhmXjnpUWAVwlQCZIy9aQicFPCq9KE5syB0egYe0dEwcMrfJPkpboNs9irXN6Nxs5u7rCNidXdmTTXCswZHAH3TpfrV5rlRrathaWu1UNDXGRum9pyn6HwT+wpvo3adwMB/E1Y6QrU7RysERa+WNhu0+24Dd1byvPcS2ro4TZuadw/8TO7QuPySxbHFpIvV4vG7sPkhmDEaKu30jwbjQxu4e09zvG6v0XpMoowAKSKO33WD8lXxsWdhuFuhPWuud1g9ipO9MNN9wEcrH8lCfTHRcaUnsDb/MJ/C2PP/wACJK5mWfrfSxQvOlC7tDw3/qnUe21BKQC2SK/HO19v6TYlJ+Uogpph9pRbCaOOUOZe0m9p4EcrILDJC/7Gohk5Au6N3g7T5ohQZ4poy5pb7TQDwN9NHDQ71HOorq0Mq6Z0bsrhY+fYq5W8raNkzcru48QeYWKxOifC7K7UcCOP5FNqtkxleisSuZlE6RMMqmy6LGZcuq/SpGVKx0WLpXVbplzpkAy1mSVXpQkkFA01SXrSE+sLvrCqhWFTUpetISZ1wzpYgGPWkvWkG6dcNQmkDDjK4jUGxHELSYVtWCAyU5Tu6S1/ELz01C6KhFBZ6ziFdTQRiWaZpafdsblx32aBvK802h9JBGYQfsgfuavdyu/4e5R48zJRxOcLXbJJrp75s3Tsa0968xmcXG66PHzUtsynKi/XY5LIblx16yT3kqiZinR0zjuCuRYW48F01FGNSkDi880sritBHgbuIV2DBxySfoil5syjaY8knQEcFt4MK6lVnw9tzop+Ub8jHlhXMq0T8PvuVd+FnkrXoiPj/gNpq17NxNlrNldtnU8gL7uZ8TCTYjnbdfrWVkpCCoHxEHVKUYyFcon1Vg+MRTQtmj9xwuDv7WnrUGL0JfTPd8f2g7Rw8NF5V6EdoujlfSSO9mT2owdweN4Hb9F7Ri1ZFFHmlcGMcQ3Md1zwJ4LlnGnRspcPLJKpMNSqmIexI9t7gONiNbi+nyVXp1jRsE/WUjUoZ0y50yKHsJ+srhqEN6YJvTooAn6wkhnTpJgUDIl0iE9I7mu538yqxCgqZUulQk5+Z8VwB3Mp4ioLdImGVDOjK4IUsQCfTBbL0ebNiqeZpR+wjO4/vJBrl62jj4c1iMJwx9RNHCz3nuDb8hvLu4AnuX0FTUcdLTtjYMrI2eQuSes701EiX8PJPS9W55ehZvJGg4NaP14LH4Xs85x1FkUjkdVVcsxuczzl/DfRbvDcLytBI18lp8mKoqPmnszNDs2ANytx4YAbALUGnzaN0HE8PFIUY+HdxJ49izXoy8UZh9AEwU3BHpYblRyRBupV5CxAsrcoQmZlz2otWXe6zQrlDgL3bwi6Jxsz4oNL81YZhxy7ltG7PkWuBZS/4V1brpORSijzWbB7k6INi2Elp3L1J+Hb9EJxTDgReya9NilBHlVPI6GRsjSWuY4OBG/Qr6hwOdtVSM6Voc2SNuZp1BDmhfPGO4bbcvb/AEY1Gagg/ltHe27T5LT0dpMxxox+22zzqNwcy7oXmzSdSw/dcfIrKGqXvmLUUdRC+KTVr2kdnJw6wV894phjoZnxSe8xxb2jgR1EWKwrZrDemTGs6wmmtHNUxCE4QBBrSJzXDmuevDmfBRiELvRBIMUO9fHX4JLnRDkkmPBErac8vkumLmp8pA/untH63qchUVDGo+jPJEejXRB1dyMh0DRGpGw33K65tk6OI8Bc9XkiyWjaeinBgC+pd/Kj83u+YHij/pIxExUNRlNiWhgPLOQ36lE9mqEQwRx8Wi7vxu1d81jPS5VfsYouMswPcwX8yFcTHrAOxVFZoJ6lt2i+iz+z8WWMDsWig3LGbtnSlolbEBa+tuCUjS/QadicBdWomAJIGUvU7bhc8zuUD8Gzn2iTzKOhSCRXZFguiwSNmgCMMp2jgFH0qeZeaaYmOewKrI0BTukBVOc9aGJIqSMGuiE4lCCCLInK4qjUuuo+zQxGKUmh71s/RoQ2jYBuBlH/ADOiAYxH7Jt1or6O3/8ApS3faSQa9t/qtbuJlJbNxDPovNvSthtpIqho98GN/a3Vh8CR3BegROsEF21pOlpHjiyzx/SdfldJijpnjoYU/oyrbYU/oVDkdCiU8hXWxq62JOEKMtDxKPRpIh6uklkKh3Rc1II9FYDLroYErAgjZ3JPb3qUWCaX8rJWOiMIvs5S9JURtO7Nmd2NGY+SHdHxutBsOw9O9x3NicO9xACE9kSqjdesWzHllXl3pHrumxCKMbo4we95vf8A4r0Um7SOw+C812nbfE//ABRebltF9M4rZo8ObZo7EUikQ6mboFPnA4rF9NgiydWI5kGMnWkKohUAfa+/FOEiCR1qmFQSmTiFOmTTKh3SFRvqLJhQRdOoZKlCZa9VH15QNRDElQqUz0NfiIunxzh24pUOiOvF2lc2BfpUR63ZI14H4hY/9U6dqqbDThldK07nsaewtd/9lUeETR6A0gDTvB4Js4zNc07i0jxFk2pFjfmfHrTHS2ugyo8wNPlJHIkeC50KLY5T5Z5NNL38QD9VRczqKwbOqPCu2NOESlDOpdyoKRD0a6pMpSRQUcyHmnhnJWZYy3e157GkqNpPCN/aWoohNEJb1XUbIt+gVwwv4Md8h5lIRSX1jNu1v5p0xFYC61exsVmSutvLG9wF/qgQp3n93/zatXs7AWQC4sS55IvfkBr3KoombVF5rjYrz/FIy7EndTIx5/mt4xpJ0F1koIc1dM/kWt8AFSeiIdCuWzVBHROKKMhuUQhiA4JJGt0Z9+GP5lVZKR/MrXvaFRq6cKhZAiBh4q9E1VhoVM1yQyVyqztUpemOKABc9MTxUH+HPPEo5HDcojDSgBUkFmNlwx6iZE5hvqtvJTgoXVUYQCYPdq1CdniRXPNv3Tr/AO5tkfEWiGYbDkrHOtvid/2ahEyWjSxvc4i6mc73j3JlPvzHgEy/sdpKDIB7Rt/aNcfijYddNbuH0CDZxzHiEe2wiBdFoLiMjwcVnzGBwHgspLZ0w4dzjmPFNLxzXXBafFMIMsnsSR5mx0o6MZrtY5rGAuNrXu7dvsVUfPJWhT9FBqzL9IP0Ckt1/kNn+s//AGJJ/CxfPD+gosTSBwCeCmkJWQR9ydlSKWVKxiZ2FaOht0bOevms6GonAXtMR+EgBNEyRca+zj3rN4Ey80zucr/NH5He1frQrZeDWQn/AFJPMoCAWZoq9Xi0Uer3hvaUVdQscNSQgeJbHU8huHG/XqE0iilLtnSAEkvIG8tYSFUh20opDZs9jyeC3z0VrG9nZPVpIoo2FxbZpBaPNYSLYbEZG9E9sTGg3u97b36styuiEItbZk5ST0j0UG9iNb8Qp2xlM2ZwF1PTshe/pHNvd2thc3ytvrYI5HRLCS2aqVggxFMMaOPo7cFWlpUqoMgb0uX+/BcZjEI0dPGDyzBQT4Q+SV3SguiFsrRu/q615VtNE9k8rRTOtchhDXC1txFhqtvOGRnP0r6PYf8AE2H3Xtd2FcfKCvH9msNxAnM1j7fxXF16hg1HUhg6UaqfSGLLg7VlnKq7If21x9w+bUS6GyrBtn3/AIT5hZjbLJblaeN/1ZcG9o5KJ77m10qeYB1ymZFLav4D+IeSzhcj2PTiRot8Lzr2j+yBFqmXTo8+Easmvlu53SG7w0PIsCQ3Ll3DT3Ru5KuUlKk1wpxT6Fv8zVn/ALh3+1n5JIRkSV/JL+k/FA1DrcVzN+ikT+rJvzUszFf9XSDv1vXHtTQ3rQUSiRFo9Ymnl+aENA5lF6P7OyCJjHnXuUGBfvP5j/NPc7TsUWD6Z/5j0xxDTiqVSHcFcYbq5FBdCVlcMy6CQ8SrVHhhuC7VaNtOOS6QAqxoTnZDBFYK3TxXKpPqtbDUq3STc01p7IknRNVRqi+O6t1lQ22iEmqtv3c1UmhQToZV054aIW+aZumY269Vo4pg4Jxp2neFP+ik66Z6KukO8/JXo3k71cdRtG4Ku/RLZVpladCpj7Xd5lE53oPO/wBo9gSE0KR9rnkFV6Q2Xah2luaUEeZwCZFFfFm5WRj72YoQ66M7RP8A2gaNzWoQQolpnR58GhqeGpt10BQWOuklcJIEaG/WFG6ye4a6pjmHerMTjiuAlJ0Z611jDyKQx7XFE8PPsntQsRngERw4kb+xC6TIbNYOIuDcX7FWoX2c8fxX8QFLiIsQ7rsqUbv2jusNPmqYQezQ08u5Eop1noZVdZOmjXENGfRUKmq61XdUKvILp2TjQ2HFGsLi7efJUYtqY5HENJ0vvBF+xOxDDw8cvqqrMEFrW7wo3ZSUWPrdpGRe1I4gcgCT4BWTtFFJHdpuCNNCEPOAE6kE9qfSYGAdfBNXVDqIUwqu4LQRT6IH6qBryViOdUTSYVklQ+olUT6lVJ50WJRobUyoVJLq7tCmqZEOc7TtJS6KXCYHiUSwllgXFB2OzODRw3lHg20YaN53pmbM5iUmaRx7lTIKMPwWUm+mqkGBP5j5rJnQpRS6AtybmR0bNv4vHgVI3Zo/f+SKFmjOJLS/5a/iPgFxGIZRDbcNHb2p5oBuRAhIBaYnJkwcMNZ1+JUgoGDgrtkrIxFkykKJvJMngDRcCyI2UU7RZDQ02B6wZmlBon+0DzBHeEalblJB3FZ6b2JC3rzD6pM0jphJr1O2ZUA9SsckdSL7JFYicqMblOx4TREgvHCCLlV5MbpYxZzt3JZnavakRR5GEXO8ryiqxyR7y4Hx1C1h5uRH+K/Y9yftdTbh43VmKtY8XavBP8YlNr28NVutlsTOUWOh+SqUXEawlw3skyrGVQxT3CZIVi2XFUOkmVd8yilkVcyJJlMdPIqcjrDTsCkleo4Pbfpub8yhGE2EcIprdpR2mbd+7dv+iHU9mjyRXCmeySd5KoxbLnRpZE4FdSozIyxKykuuEooBlkk9cToY8lczKDOkXp2FE+Zc6RQZ1zOhsKLBkUUj9FHnTXPSsKI8Siu243jgsxi8eZuZvvN+nBauV1wgNfFYk8DvUs1QNpKi7QVabKhD3ZH2+Fx06irLZVLOmD0FGTJxfmVGJytiWzbWRYpGP2n2TmkLpmEvF93IcllY8CnJ+yI8F6lBjZjuDf6Js2LRu1yt8AuqHpUaL+BS2zzuLZqRx1s0cTx7lrcFwtsLQ0G/EnrT5qrO72fkr9KywUTnaE4RjwuxyWCUs6gkcqkkqyGiw+RQOeoTIq1VUhqSFJ0iSebgN50CKUMQaAheF0/xu3ncjMTb6KznbsvUzM3YEXgNmgBBcSqvV4SRa/C+66WyNdLUZ3S5Q1tg0NaQSeOpKmX+Ktmb2HsyRkUrhG0EkeJJ+SgdVNduAA58Vi/yIoFBsd0i70ioVWJRsuSQB12Qb/N1OXBodvIGgPNEPfL6KcDT9IkqHrTPvj5JLXInFlkyJvSKEuTS5WRZOZFzpFAHpZkDsnzrhcosykAPFTKaitgk2THcqVYy4Vz4VWkCE8lZokZbEqYWIPceSHU1QQcjjqOPMLS1kKzOKUx3jeN3YgtOglBMrrXXCyzK8s1cLjmOHajFHWgi4NxzQ0WnZPW0eYIacOPMow2rBTHShQkaL+EFJR2Vw6KF1UAqstUqEyxLKqT5FUqq5rd5AVf1u+vgnTBySRamnyhV6WMyPuVXjaXG54o3QQ5R1lUlic7k2y7ENwCK0cdteKqUkFtSiLUm7FwHbR0b5Y7MdYtu6x+LTd1KlslXubERuGc+NgCDyRgye0g9Mzoa0tHuVDcxHDMP181g553EdfYUkxPMSXHQbusobXY61t9eH/4ieI4F0rCIzkcPdHwnqPLtXmVc6Rkro5RZ7TYj9cFl5eSmVZercTfKbu7ghUhs64VqMqKtG7sXXFJaCT0N6c8z4pKC6SvFEWe0FyaVxdCRmkdSsrNNTX9p5ys58+xGKekhF3BoOlwSSd3ak3oATSQX1Pd+adI2yu77n9diilZp3rzPWTnKzZFRh3gqCU2KdIDfROGuj2m/UCV2eDuAn0oVLUIrYbo/PSvaNRcfreh88JPBbDMpPTa7t6A1UUkDi6I+zxbvHgtnU0gN+GqF1dKLKoyAEUmPXHtDwVsYwzmUDxKhMbrtHsn5KJrgtME+AptBuTGmjcCUMqsXldo3S/LUqByJUGG29o+95J0oic2yGioyDnecz+vh/dFIoCVbgo1cjgyqHKxUMpaW2pRemg4lRUsXEq/EsyiaFqe9y413BRVB0txJSk8Y2KrY6Bt1W2gpwzoZ/wDTkF/wu3/MfNFaOGw7lBtCzNTyjk2/hY/RedCX+d/0uXAxEfDRZna/ZE1bmviyiS2V1zlu34Tex1GqNYRLmhjPNjfJEaZ1nBV5zcPTQvo86Po0rR7kkL+rM4fPKg+0uyNXStD5WAs+/GczWnk7QWXuMUlyT3KaZrXtLHgFrgQQRcEHgV6mjLJnzLnSXt//APOcO/0j4rqrRWZBlVqipc7tb20ulU0hZJk38usHcUXgpGtAA3jU8lnWzJF+BjQ2wGm5V68gC26/kn9JcaOFtdQh0zhfTUczxKy95VAuK2K6Y86BInmmX3LzbNSnLo4doF1wuKfVO3HkR5hNqve712fjfYpHSXnTMBft+iry0ztbkKZtaW8FTnqd5Oi6eiBldE4X/IoDVTs4u+RVnHsUYAXXNhpcOO/kADZZF2JPJu1rQOFyb2WkINkykl0KyPzG2pHZZcbRB29oUmEVjZRbLZ433OlkYhpxvvf9cEm2tFLYPiogOA8FchpSr8NN1KDFqpsDMx7ABxKnbG6RLHFZcZbldYyTaSTNqNOrkj1BirnsDmtGX9b1coNdIUkzQxyADcVMJGnqQaPEPZJe43vo36IVV4nV5S5pygcgL26tFCRRsmyDd+j3p0LM0l7aNAHedfyQDB8TMrQSbkaFajDosrdd7jc34dS5/wAmVRoce2XGCyH4861PJ1tt/uICJAoTtLcxBo+KRg8Vxee5Ip8COFx5YWN/hb5K0HWTGgAW5D+y5KdE7/5A+gtA8aaAacFN0iF9PZwF92/ssr1M4u1tYL1UYNFi/WuLuUJKhUVsU+1j7HLvwn8JSSQ+sSIKX7Idv/yXZfi7R/1SSXN+R+prAhm3+P1UI+iSS89mhSq/dPd5hSVW/wAUkl1/i8ZL6VnqhiHuldSXUgMhtj9g38TFm4dw/pXUl0efDD0LuFfbd618XBJJZen7GsOIJRblmdufcj7XeSSSiP7CnwxBWp2V+w/qKSS6/Thj5/sWXb+9EHfYv/CfJJJc0TpkCdmP3n64L0iHckkuP8rqHElG9C9oN0X86NJJcvl+w3wMOTZfy80kk1/2DXBkPvyfh+oWgp/dC6kvTXTFj0kklqSf/9k=

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends: false
  #友情链接1: http://localhost:4000/
  #友情链接2: http://localhost:4000/
  #友情链接3: http://localhost:4000/
  #友情链接4: http://localhost:4000/
  #友情链接5: http://localhost:4000/
  #友情链接6: http://localhost:4000/

aboutme: 希望<br><br>你今天也是开心的鸭<br>